### Python 기본 2

#### tuple

In [1]:
1 in (1, 2, 3)

True

In [2]:
(1, 2, 3) + (4, 5)

(1, 2, 3, 4, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [5]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [6]:
type(range(5))

range

In [7]:
(1, 2, 3) * 5

(1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3)

In [8]:
# 시퀀스 자료형

fruit = ["사과", "포도", "홍시"]

user_input = input("좋아하는 과일은? ")

if user_input in fruit:
    print("정답입니다.")
else:
    print("오답입니다.")

정답입니다.


In [9]:
menu = {'김밥':2000, '라면':2000, '돈까스':2000}

user = input()

if user in menu:
    print("있는 메뉴")
else:
    print("없는 메뉴!!!")

없는 메뉴!!!


#### 2024-12-24

In [1]:
# 복습하기
a = b = 10
c, d = 30, 'Hello'
e = 35
print(a, b, c, d, e)

10 10 30 Hello 35


In [10]:
movie_rank = ["닥터 스트레인지", "스플릿", "럭키"]
movie_rank.append("배트맨")
print(movie_rank)
movie_rank.insert(1, "슈퍼맨")
print(movie_rank)
movie_rank.pop(3)
print(movie_rank)
movie_rank.pop(2)
movie_rank.pop(2)
# del movie_rank[2:4] # del은 메모리에서 아예 지워버리는 것. 사실 python에서 리스트 작업할 때 잘 쓰진 않는다.
print(movie_rank)

['닥터 스트레인지', '스플릿', '럭키', '배트맨']
['닥터 스트레인지', '슈퍼맨', '스플릿', '럭키', '배트맨']
['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']
['닥터 스트레인지', '슈퍼맨']


In [14]:
# 언패킹
temp = ('apple', 'banana', 'cake')
a, b, c = temp # 언패킹 (Unpacking) # 시퀀스 자료형 특징?
print(a, b, c) # ㅇㅁㅇ!!

temp2 = {'apple', 'banana', 'cake'}
a2, b2, c2 = temp2 #?
print(a2, b2, c2)

temp3 = ['apple', 'banana', 'cake']
a3, b3, c3 = temp3
print(a3, b3, c3)

apple banana cake
cake banana apple
apple banana cake


In [15]:
phone_number = "010-1234-5678"
phone_number1 = phone_number.replace("-", " ")
print(phone_number1)

010 1234 5678


In [ ]:
# input 여러개 한 번에 받기
a, b, c = input().split()
s = int(a) + int(b) + int(c)

print(s)

In [ ]:
a, b, c = map(int, input().split(' '))

In [17]:
# 이름, 키, 나이를 입력 받아 인쇄하기
a, b, c = input().split()
print(a, b, c)
b, c = float(b), int(c)
print(type(a), type(b), type(c))
print(f"name = {a} height = {b} age = {c}")

박지민 178.5 28
<class 'str'> <class 'float'> <class 'int'>
name = 박지민 height = 178.5 age = 28


In [18]:
# 5명의 학생이 가지고 있는 예금의 합
d = {'kim' : 34000, 'lee' : 12000, 'park' : 1200, 'lew' : 0, 'song' : 3420}

print(sum(d.values()))

50620


In [19]:
# 문자열을 입력 받아 각 문자들로 구성된 리스트로 반환하는 make_list 함수를 정의
def make_list(string):
    lst = []
    for i in range(len(string)):
        lst.append(string[i])
    return lst
make_list("abcd")

['a', 'b', 'c', 'd']

In [20]:
# +
def make_list (string):
    return list(string)
make_list("abcd")

['a', 'b', 'c', 'd']

In [23]:
# 함수 안의 변수와 밖의 변수, 그 영향력
# 함수 안의 변수와 연결하는 법
a = 1
def vartest():
    global a
    a = a+1

vartest()
print(a)
#----------------
a = 1
def vartest(a):
    a = a + 1
    return a

a = vartest(a)
print(a)

2
2


In [26]:
# map
# map(function, iterable)

# 모든 요소를 1씩 증가시키기

myList = [1, 2, 3, 4, 5]
# for 함수 이용
myList_copy = myList.copy()
for i in range(len(myList_copy)):
    myList_copy[i] += 1
print(myList_copy)

# 함수 정의?
myList_copy = myList.copy()
def add_one(n):
    return n+1
for i in range(len(myList_copy)):
    myList_copy[i] = add_one(myList_copy[i])
print(myList_copy)

# map 함수 이용
myList_copy = myList.copy()
myList_copy = list(map(add_one, myList_copy))
print(myList_copy)

[2, 3, 4, 5, 6]
[2, 3, 4, 5, 6]
[2, 3, 4, 5, 6]


In [41]:
# 내장 함수를 할용한 예제
# map, round 사용
# 실수 값들의 일괄적 정수화
from functools import partial # 응용

f = (3.14, -7.934, 1.24, 0.01234)

print(list(map(round, f)))
print(list(map(lambda x: round(x, 2), f))) # 응용
print(list(map(partial(round, ndigits=2), f))) # 응용

[3, -8, 1, 0]
[3.14, -7.93, 1.24, 0.01]
[3.14, -7.93, 1.24, 0.01]


In [39]:
number_1 = [1, 2, 3, 4, 5]
number_2 = [1, 2, 3, 4, 5]

def cal(x, y, t='+'):
    if t == '+':
        return x+y
    elif t == '-':
        return x-y
    elif t == '*':
        return x*y
    elif t == '/':
        return x/y
    elif t == '//':
        return x//y
    elif t == '%':
        return x%y
    else:
        return x**y
    
list(map(cal, number_1, number_2))

[2, 4, 6, 8, 10]

In [48]:
# zip
# zip 함수는 길이가 가장 짧은 배열을 기준으로 같은 인덱스 번호끼리 매칭되어 짝지어진다
# 이미지의 색상별 데이터를 묶어서 24bpp RPG 만들기

r = (52, 255, 39, 132)
g = (19, 63, 227, 197)
b = (0, 68, 255, 187)

img = list(zip(r,g,b)) # ㅇㅁㅇ!!

print(img)

[(52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187)]


In [58]:
# +)
def make_image(r, g, b, width, height):
    imgTemp = []
    for i in range(width):
        for j in range(height):
            imgTemp+=zip(r,g,b)
    return imgTemp

r = (52, 255, 39, 132)
g = (19, 63, 227, 197)
b = (0, 68, 255, 187)
p = {r, g, b}
img = make_image(r, g, b, 4, 4)
print(img)


# +)
def make_image(r, g, b, width, height):
    pixels = list(zip(r, g, b))
    image = []
    for row_idx in range(0, width * height, width):
        row = pixels[row_idx:row_idx+width]
        image.append(row)
    return image

r = (1, 2, 3, 4, 5, 6, 7, 8, 9)
g = (11, 22, 33, 44, 55, 66, 77, 88, 99)
b = (1, 2, 3, 4, 5, 6, 7, 8, 9)

image = make_image(r, g, b, 3, 3)
print(image)

[(52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187), (52, 19, 0), (255, 63, 68), (39, 227, 255), (132, 197, 187)]
[[(1, 11, 1), (2, 22, 2

In [54]:
# enumerate
# enumerate(iterable [, start=0])
# start는 시작번호(생략 시 0)이며 결과는 enumerate 타입
# item들의 번호를 부여하여 (idx, value)의 튜플 쌍을 생성

# 과일 품목별 일련번호 부여하기
# 튜플 f 에 있는 과일들을 1번ㄴ부터 차례대로 보기와 같이 인쇄되도록 번호를 부여하라
# zip과 range를 이용하는 방법과 enumerate를 이용하는 방법이 가능하다
# 단, 결과는 dict로 생성되어야 한다.

# enumerate 사용하기
f = ('apple', 'orange', 'banana', 'mango')

tag = dict(enumerate(f, 1)) # ㅇㅁㅇ...!

print(tag)

{1: 'apple', 2: 'orange', 3: 'banana', 4: 'mango'}


In [57]:
# filter
# 반복 가능한 객체에서 특정 조건에 맞는 요소만 가져옴
# filter에 지정한 함수의 반환값이 True일 때만 해당 요소를 가져옴
# filter(함수, 반복가능한객체)

# 본인이 사용할 필터 조건 정의해놓고 매핑해서 쓰기 좋음.

def f(x):
    return x > 5 and x < 10 

a = [8, 3, 2, 10, 15, 7, 1, 9, 0, 11]
list(filter(f, a))

[8, 7, 9]

In [62]:
# lambda

myList = [1, 2, 3, 4, 5]

result = list(map(lambda x: x + 1, myList))
print(result)

[2, 3, 4, 5, 6]


In [63]:
numbers = [1, 2, 3, 4]
squared = list(map(lambda x: x**2, numbers))
print(squared)

[1, 4, 9, 16]


In [66]:
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x%2 == 0, numbers))
print(even_numbers)

[2, 4]


In [81]:
points = [(1, 2), (3, 4), (5, 1)]
sorted_points = sorted(points, key=lambda x: x[1]) ####!!!!
print(sorted_points)

[(5, 1), (1, 2), (3, 4)]


In [82]:
# + sorted
a = [3, 7, 32, 9, 7]

new_a = sorted(a)
print(a)
print(new_a)

[3, 7, 32, 9, 7]
[3, 7, 7, 9, 32]


In [83]:
# + sorted
a = [3, 7, 32, 9, 7]

new_a = sorted(a, reverse=True)
print(a)
print(new_a)

[3, 7, 32, 9, 7]
[32, 9, 7, 7, 3]


In [85]:
# + sorted
a = [3, 7, 32, 9, 7]

new_a = sorted(a, key=lambda x: 1/x)
print(a)
print(new_a)

[3, 7, 32, 9, 7]
[32, 9, 7, 7, 3]


In [87]:
# + sorted
a = ['pineapple', 'banana', 'kiwi']

new_a = sorted(a, key=lambda x: len(x))
print(a)
print(new_a)

['pineapple', 'banana', 'kiwi']
['kiwi', 'banana', 'pineapple']


In [94]:
my_dict = {3: 'c', 1: 'a', 2: 'b'}

new_dict = sorted(my_dict)
# 원본에서 뽑아서 새로 정렬한 리스트를 만드는 것이기 때문에 sorted하면 리스트만 나옴
# 원래 딕셔너리는 정렬하는 데이터 종류가 아님
print(my_dict)
print(new_dict)
# 그러나 key 지정으로 변주는 줄 수 있음
new_dict = sorted(my_dict.items(), key=lambda x: x[1])
print(new_dict)

new_dict = sorted(my_dict.values())
print(new_dict)

new_dict = sorted(my_dict.keys())
print(new_dict)

{3: 'c', 1: 'a', 2: 'b'}
[1, 2, 3]
[(1, 'a'), (2, 'b'), (3, 'c')]
['a', 'b', 'c']
[1, 2, 3]


In [96]:
points = [(1, 2), (3, 4), (5, 1)]

sorted_points = sorted(points, key=lambda x: x[1])
print(sorted_points)

[(5, 1), (1, 2), (3, 4)]


#### 모듈

In [97]:
import math

In [98]:
math.pow(2, 3) # 2의 3제곱

8.0

In [102]:
import math as m

m.pow(2, 4)
m.sqrt(9)

3.0

In [101]:
from math import pow

pow(2, 5)

32.0

In [106]:
import random
help(random)

Help on module random:

NAME
    random - Random variable generators.

MODULE REFERENCE
    https://docs.python.org/3.13/library/random.html

    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
        bytes
        -----
               uniform bytes (values between 0 and 255)

        integers
        --------
               uniform within range

        sequences
        ---------
               pick random element
               pick random sample
               pick weighted random sample
               generate random permutation

        distributions on the real line:
        ------------------------------
               uniform
               triangular
               normal (Gaussian)
               l

In [117]:
# 로또 번호 추첨기 (무작위 생성된 6개의 숫자 출력)
import random

result = []
while 1:
    if len(set(result)) == 6:
        break
    result = [random.randint(1, 45) for _ in range(6)]
print(result)

result = []
while 1:
    if len(result) == 6:
        break
    
    num = random.randint(1, 45)
    if num not in result:
        result.append(num)
print(result)

[32, 2, 25, 28, 39, 1]
[45, 29, 18, 15, 38, 7]


In [119]:
random.sample(range(1, 46), 6)

[21, 2, 44, 43, 35, 1]

In [3]:
# 모듈 업그레이드 미션

import random

sel = ['가위', '바위', '보']
def checkWin(p1, p2):
    is_win = True
    if p1 == '가위':
        if p2 == '바위': is_win = False
    elif p1 == '바위':
        if p2 == '보': is_win = False
    elif p1 == '보':
        if p2 == '가위': is_win = False
    else:
        print("잘못된 입력입니다")
        return False
    
    if is_win:
        print("이겼습니다!")
        return is_win
    else:
        print("졌습니다...")
        return is_win

def continueConfirm():
    confirm = input("계속하시겠습니까? (Y/N) : ")
    if confirm in ["Y", "y"]:
        return True
    elif confirm in ["N", "n"]:
        return False
    else:
        print("잘못된 입력입니다")
        return False

while True:
    user = input("가위, 바위, 보 : ")
    com = sel[random.randint(0, 2)]
    if checkWin(user, com):
        if continueConfirm():
            continue
        else:
            break

이겼습니다!
이겼습니다!


#### 클래스

In [4]:
class Dog:
    species = "Doberman"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        return f'{self.name} is barking'

In [5]:
dog1 = Dog('Happy', 3)

In [6]:
type(dog1)

__main__.Dog

In [7]:
dog1.name

'Happy'

In [8]:
dog1.age

3

In [9]:
dog2 = Dog('Max', 5)
dog2.bark()

'Max is barking'

In [10]:
class FourCal:
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2
    def add(self):
        result = self.num1 + self.num2
        return result
    def sub(self):
        result = self.num1 - self.num2
        return result
    def mul(self):
        result = self.num1 * self.num2
        return result
    def div(self):
        result = self.num1 / self.num2
        return result

In [11]:
a = FourCal(7, 3)

In [15]:
a.num1

7

In [13]:
print(a.add())
print(a.sub())
print(a.mul())
print(a.div())

10
4
21
2.3333333333333335


In [16]:
# 상속 
class AdvancedFourCal(FourCal):
    def pow(self):
        return self.num1 ** self.num2

In [17]:
c = AdvancedFourCal(4, 2)

In [18]:
c.pow()

16

In [19]:
c.add()

6

In [23]:
c1  = AdvancedFourCal(4, 0)
c1.div()

ZeroDivisionError: division by zero

In [20]:
# 상속 후 재정의
# method overrideing -> 버그패치
# 상속 -> 업그레이드
class SafeFourCal(FourCal):
    def div(self):
        if self.num2 == 0:
            return 0
        else:
            return self.num1 / self.num2

In [21]:
e = SafeFourCal(5, 0)
e.div()

0

#### 2024-12-27

In [1]:
# 조건부 표현식
score = int(input("점수를 입력하세요: "))
message = "success" if score >= 60 else "failure"
print(message)

success


In [3]:
# 리스트 컴프리헨션
numbers = [1, 2, 3, 9]
squares = [x**2 for x in numbers]
print(squares)

[1, 4, 9, 81]


In [8]:
numbers = [1, 2, 3, 4, 5, 6, 7]
even_numbers = [x for x in numbers if x%2 == 0]
even_numbers_squared = [x**2 for x in numbers if x%2 == 0]
print(even_numbers)
print(even_numbers_squared)

[2, 4, 6]
[4, 16, 36]


#### Numpy

In [10]:
# NumPy
import numpy as np

In [11]:
np.__version__

'2.2.0'

In [12]:
a_list = [1, 2, 3, 4]
a_list

[1, 2, 3, 4]

In [13]:
type(a_list)

list

In [14]:
int_arr = np.array([1, 2, 3, 4])
int_arr

array([1, 2, 3, 4])

In [15]:
print(int_arr) # comma가 없다...

[1 2 3 4]


In [16]:
type(int_arr)

numpy.ndarray

In [20]:
list_data = [1, 2.2, '2', 3]

arr = np.array(list_data)
print(arr)
print(type(arr))

['1' '2.2' '2' '3']
<class 'numpy.ndarray'>


In [21]:
arr1 = np.arange(1, 10, 2)
arr1

array([1, 3, 5, 7, 9])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr = np.zeros((2, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                [[9,10,11,12], [13,14,15,16]],
                [[9,10,11,12], [13,14,15,16]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
3
(3, 2, 4)


In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr.reshape(2, 5))
print(arr.reshape(2, -1))
print(arr.reshape(5, -1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [42]:
a = [1,2,3]
b = [4,5,6]

np_a = np.array(a)
np_b = np.array(b)

print(type(a), type(b))
print(type(np_a), type(np_b))

print(a*3)
print(np_a*3)
print(np_a*np_b)

<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
[ 4 10 18]


In [45]:
# 넘파이 배열 연산하기
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 데이터를 모두 2배로 변경

# 반복문으로 구현
for i in range(len(data)):
    data[i] *= 2

print(data)

# numpy로 구현 # (잘 구별 안 갈 수 있지만 얘가 훨씬 빠르고 편하다)
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x = np.array(data)
print(x*2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [50]:
c = np.array([[0, 1, 2], [3, 4, 5]])

print(len(c))
print(len(c[0]))
print()
print(c.ndim)
print(c.shape)
print(c.size)

2
3

2
(2, 3)
6


In [52]:
# 배열의 인덱싱

a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])

2
4


In [53]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print(a[0][0], a[0][1], a[1][2])

0 1 5


In [61]:
# 배열의 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a[0])
print(a[0, 1], a[1][1])
print(a[:, 1]) # 오...!
print(a[1, 1:])
print(a[:2, :2])

[0 1 2 3]
1 5
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [62]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2*a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


#### Fancy Indexing

In [63]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [68]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([x%2 == 0 for x in a])
idx2 = (a%2 == 0)

print(a[idx])
print(a[idx2]) # a[a % 2 == 0]

[0 2 4 6 8]
[0 2 4 6 8]


In [69]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [71]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 5, 5, 5, 5])
a[idx]

array([11, 11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 66, 66, 66, 66])

In [88]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[:, [0, 3]])
print(a[:, [True, False, False, True]])
print()
print(a[[2, 0, 1], :])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [98]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
 
# 배열에서 3의 배수를 찾아주세요.
print(x[x%3 == 0])
 
# 배열에서 4로 나누면 1이 남는 수를 찾아주세요.
print(x[x%4 == 1])
 
# 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.
print(x[(x%3 == 0) & (x%4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


#### Pandas

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [5]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
print(s)
print(type(s))

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
s.values

array([ 3, -5,  7,  4])

In [8]:
print(s[0])
# 실행하는데 문제는 없지만, 이제는 지원 안 할 방법이다

3


C:\Users\USER\AppData\Local\Temp\ipykernel_1672\287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [9]:
# 대신 이것 이용
print(s['a'])

3


In [10]:
s

a    3
b   -5
c    7
d    4
dtype: int64

In [11]:
s * 3

a     9
b   -15
c    21
d    12
dtype: int64

In [17]:
df = pd.DataFrame([['부산광역시', '051', 3364358],
                   ['전라남도', '061', 1840921],
                   ['강원도', '033', 1535530]])
df

0    1        2
0  부산광역시  051  3364358
1   전라남도  061  1840921
2    강원도  033  1535530

In [23]:
df = pd.DataFrame({'Division': ['부산광역시', '전라남도', '강원도'],
                   'Code': ['051', '061', '033'],
                   'Population': [3364358, 1840921, 1535530]})
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [24]:
print(df)

  Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530


In [25]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [26]:
df.columns

Index(['Division', 'Code', 'Population'], dtype='object')

In [31]:
df.values

array([['부산광역시', '051', 3364358],
       ['전라남도', '061', 1840921],
       ['강원도', '033', 1535530]], dtype=object)

In [32]:
df.set_index('Division')

Code  Population
Division                 
부산광역시     051     3364358
전라남도      061     1840921
강원도       033     1535530

In [34]:
df = pd.read_csv("./heroes.csv")
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [35]:
# 지수 표현식이 아닌 소수 표현식으로 사용하겠다는 옵션 설정
pd.options.display.float_format = '{:.0f}'.format
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [37]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [38]:
df.tail()

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [39]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [42]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [44]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [45]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [51]:
df['나이'].nlargest(3)

0    58
1    45
4    33
Name: 나이, dtype: int64

In [52]:
df.nlargest(3, '나이')

이름  나이     직업     국적    키          재산
0  아이언맨  58    CEO     미국  174 11500000000
1    토르  45      신  아스가르드  190         NaN
4    헐크  33  핵물리학자     미국  270  1000000000

In [55]:
df[['이름', '직업', '나이']].nlargest(7, '나이')

이름     직업  나이
0   아이언맨    CEO  58
1     토르      신  45
4     헐크  핵물리학자  33
6  블랙위도우    스파이  32
3   원더우먼     공주  27
5   캡틴마블    파일럿  25
2  스파이더맨   고등학생  18

In [56]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [57]:
df.iloc[0]

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: 0, dtype: object

In [58]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [61]:
df.iloc[:5, :3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [62]:
df2 = df.copy()
df2.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [64]:
df2.loc['a':'b']

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [65]:
df2.loc['a', '이름']

'아이언맨'

In [66]:
df2.loc['a':'b', '이름': '직업']

이름  나이   직업
a  아이언맨  58  CEO
b    토르  45    신

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [69]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [71]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [70]:
# is null fancy indexing
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [86]:
cond = df['나이'] > 30
print(cond)
print(df[cond])

df[df['나이'] > 30].loc[:, ['이름', '나이', '직업']]

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool
      이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
6  블랙위도우  32    스파이    러시아  170    50000000


이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [78]:
cond = (df['나이'] > 30) & (df['나이'] < 50)
print(df[cond])

      이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000


In [88]:
df.sort_values('키') # 오름차순

이름  나이     직업     국적    키          재산
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
0   아이언맨  58    CEO     미국  174 11500000000
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [90]:
df.sort_values('재산', ascending=False) # 내림차순

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000
2  스파이더맨  18   고등학생     미국  177         600
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [92]:
df2['국적'] = '대한민국'
df2

이름  나이     직업    국적    키          재산
a   아이언맨  58    CEO  대한민국  174 11500000000
b     토르  45      신  대한민국  190         NaN
c  스파이더맨  18   고등학생  대한민국  177         600
d   원더우먼  27     공주  대한민국  178         NaN
e     헐크  33  핵물리학자  대한민국  270  1000000000
f   캡틴마블  25    파일럿  대한민국  170   340000000
g  블랙위도우  32    스파이  대한민국  170    50000000

In [93]:
import random
df2['전투력'] = list(random.randint(0, 100) for _ in range(7))
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   52
b     토르  45      신  대한민국  190         NaN   86
c  스파이더맨  18   고등학생  대한민국  177         600    6
d   원더우먼  27     공주  대한민국  178         NaN   14
e     헐크  33  핵물리학자  대한민국  270  1000000000   26
f   캡틴마블  25    파일럿  대한민국  170   340000000   82
g  블랙위도우  32    스파이  대한민국  170    50000000   49

In [94]:
df2['전투력'] = df2['전투력'] -5
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   47
b     토르  45      신  대한민국  190         NaN   81
c  스파이더맨  18   고등학생  대한민국  177         600    1
d   원더우먼  27     공주  대한민국  178         NaN    9
e     헐크  33  핵물리학자  대한민국  270  1000000000   21
f   캡틴마블  25    파일럿  대한민국  170   340000000   77
g  블랙위도우  32    스파이  대한민국  170    50000000   44

In [96]:
df2.columns = ['Name', 'Age', 'Job', 'Nationality', 'Height', 'Property', 'CP']
df2

Name  Age    Job Nationality  Height    Property  CP
a   아이언맨   58    CEO        대한민국     174 11500000000  47
b     토르   45      신        대한민국     190         NaN  81
c  스파이더맨   18   고등학생        대한민국     177         600   1
d   원더우먼   27     공주        대한민국     178         NaN   9
e     헐크   33  핵물리학자        대한민국     270  1000000000  21
f   캡틴마블   25    파일럿        대한민국     170   340000000  77
g  블랙위도우   32    스파이        대한민국     170    50000000  44

In [105]:
print(df[df['직업'] =='CEO'].index)

Index([0], dtype='int64')


In [106]:
df2.drop(index=['a'])

Name  Age    Job Nationality  Height   Property  CP
b     토르   45      신        대한민국     190        NaN  81
c  스파이더맨   18   고등학생        대한민국     177        600   1
d   원더우먼   27     공주        대한민국     178        NaN   9
e     헐크   33  핵물리학자        대한민국     270 1000000000  21
f   캡틴마블   25    파일럿        대한민국     170  340000000  77
g  블랙위도우   32    스파이        대한민국     170   50000000  44

In [107]:
df2

Name  Age    Job Nationality  Height    Property  CP
a   아이언맨   58    CEO        대한민국     174 11500000000  47
b     토르   45      신        대한민국     190         NaN  81
c  스파이더맨   18   고등학생        대한민국     177         600   1
d   원더우먼   27     공주        대한민국     178         NaN   9
e     헐크   33  핵물리학자        대한민국     270  1000000000  21
f   캡틴마블   25    파일럿        대한민국     170   340000000  77
g  블랙위도우   32    스파이        대한민국     170    50000000  44

In [108]:
df2.drop(index=['a'], inplace=True) # 원본 변형

In [109]:
df2

Name  Age    Job Nationality  Height   Property  CP
b     토르   45      신        대한민국     190        NaN  81
c  스파이더맨   18   고등학생        대한민국     177        600   1
d   원더우먼   27     공주        대한민국     178        NaN   9
e     헐크   33  핵물리학자        대한민국     270 1000000000  21
f   캡틴마블   25    파일럿        대한민국     170  340000000  77
g  블랙위도우   32    스파이        대한민국     170   50000000  44

In [110]:
df2.drop(columns='CP', inplace=True)
df2

Name  Age    Job Nationality  Height   Property
b     토르   45      신        대한민국     190        NaN
c  스파이더맨   18   고등학생        대한민국     177        600
d   원더우먼   27     공주        대한민국     178        NaN
e     헐크   33  핵물리학자        대한민국     270 1000000000
f   캡틴마블   25    파일럿        대한민국     170  340000000
g  블랙위도우   32    스파이        대한민국     170   50000000

In [111]:
df2.dropna(axis=1)

Name  Age    Job Nationality  Height
b     토르   45      신        대한민국     190
c  스파이더맨   18   고등학생        대한민국     177
d   원더우먼   27     공주        대한민국     178
e     헐크   33  핵물리학자        대한민국     270
f   캡틴마블   25    파일럿        대한민국     170
g  블랙위도우   32    스파이        대한민국     170

In [113]:
df2.fillna(0)

Name  Age    Job Nationality  Height   Property
b     토르   45      신        대한민국     190          0
c  스파이더맨   18   고등학생        대한민국     177        600
d   원더우먼   27     공주        대한민국     178          0
e     헐크   33  핵물리학자        대한민국     270 1000000000
f   캡틴마블   25    파일럿        대한민국     170  340000000
g  블랙위도우   32    스파이        대한민국     170   50000000

In [115]:
df2.fillna(0)

Name  Age    Job Nationality  Height   Property
b     토르   45      신        대한민국     190          0
c  스파이더맨   18   고등학생        대한민국     177        600
d   원더우먼   27     공주        대한민국     178          0
e     헐크   33  핵물리학자        대한민국     270 1000000000
f   캡틴마블   25    파일럿        대한민국     170  340000000
g  블랙위도우   32    스파이        대한민국     170   50000000

In [118]:
df2['Property'].fillna(df2['Property'].mean())

b    347500150
c          600
d    347500150
e   1000000000
f    340000000
g     50000000
Name: Property, dtype: float64

In [120]:
df2.fillna(method='bfill')

C:\Users\USER\AppData\Local\Temp\ipykernel_1672\2667140817.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill')


Name  Age    Job Nationality  Height   Property
b     토르   45      신        대한민국     190        600
c  스파이더맨   18   고등학생        대한민국     177        600
d   원더우먼   27     공주        대한민국     178 1000000000
e     헐크   33  핵물리학자        대한민국     270 1000000000
f   캡틴마블   25    파일럿        대한민국     170  340000000
g  블랙위도우   32    스파이        대한민국     170   50000000

In [119]:
df2.fillna(method='ffill')

C:\Users\USER\AppData\Local\Temp\ipykernel_1672\2637084966.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill')


Name  Age    Job Nationality  Height   Property
b     토르   45      신        대한민국     190        NaN
c  스파이더맨   18   고등학생        대한민국     177        600
d   원더우먼   27     공주        대한민국     178        600
e     헐크   33  핵물리학자        대한민국     270 1000000000
f   캡틴마블   25    파일럿        대한민국     170  340000000
g  블랙위도우   32    스파이        대한민국     170   50000000

In [121]:
df2['Property'].mean()

np.float64(347500150.0)